trino_dbt_profile:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: localhost
      port: 8080
      user: admin
      database: iceberg
      schema: bronze    # Change this if you're running a different schema
      threads: 4